add hw 5 - docker and pipenv/poetry
NankuF/Otus.Base-Python pull request #1
Opened 2021-06-18 11:48 UTC by NankuF

2021-06-18 18:10 UTC, mahenzon requested changes
ok, but needs a couple of changes

2021-06-18 18:10 UTC, mahenzon commented on homework_05/Dockerfile
> +RUN pip install -U pip setuptools poetry
зачем нам ставить поэтри, если зависимости дальше ставим из requirements.txt?

2021-06-18 18:10 UTC, mahenzon commented on homework_05/web-app/app.py
> +    return "Hello web_app"
new line

2021-06-19 04:19 UTC, NankuF commented on homework_05/Dockerfile
> +RUN pip install -U pip setuptools poetry
done

2021-06-19 04:19 UTC, NankuF commented on homework_05/web-app/app.py
> +    return "Hello web_app"
done

2021-06-19 16:28 UTC, merged